#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

declare APP="$1" REV="$2"

# Don't write the revision if there is no git repository.
if [[ -d "$DOKKU_ROOT/$APP/refs" ]]; then
  echo $(cat "$DOKKU_ROOT/$APP/SLACK_NEW_REV" 2> /dev/null) > "$DOKKU_ROOT/$APP/SLACK_OLD_REV"
  echo "$REV" > "$DOKKU_ROOT/$APP/SLACK_NEW_REV"
fi
